version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
install:
  - dotnet --info
  - ps: choco install docker-compose
before_build:
  - dotnet restore Modix\Modix.csproj
  - dotnet restore Modix.Data\Modix.Data.csproj
  - 7z a deploy-script.zip before-deploy.ps1
build:
  project: Modix.sln
  verbosity: minimal
test: off  
after_build:
  - ps: |
      if(-not [System.String]::IsNullOrWhitespace($env:APPVEYOR_PULL_REQUEST_NUMBER)) {	return; }
      $tag = $env:APPVEYOR_REPO_BRANCH
      if([System.String]::IsNullOrWhitespace($tag)) { $tag = "untagged" }
      docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
      docker tag modix cisien/modix:$tag
      docker push cisien/modix:$tag
artifacts:
  - path: deploy-script.zip
    name: deploy-script
deploy:
  - provider: Environment
    name: docker
    on:
      branch: master
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOCKER_USER:
    secure: ry9x9cQ9gzMNaPOd45RSHQ==
  DOCKER_PASS:
    secure: AXXeju7g+0ZE1ZMW2TKcXfW6+CMT70ZDh5iWYE5Bg80=
  ModixToken:
    secure: BWrrOxIXH+Aq+iQLbCR5SUS28lWtWIm/ideML7d5k7oppYgFDN7Kz68SVjUBbLPEv0hV9REAMaRK4vr0Ng8vng==
  ReplServiceToken:
    secure: GroejrzfkoqNfBomrM4kTrBhT9PoueDewcScZe81dYrqU42xc4WRH2gbNib7wDTz
  SOToken:
    secure: ikKVUonT4VkpFzI4GhMi3ZNqHzgA6DokzWXvm0G4DUg=
  log_webhook_token:
    secure: /QjuIMGkGJIDgoyw+zeIsQQKjcbnrmydGAjcOhzYvFPHy2CFoev9vd2Bq8gv+oA/dUVv8mFShqPqvzFq+1PkwdUMIYVB21wcTRENTA4FjjQ=
  ConnectionString: Data Source=c:\app\config\sqlite.db;Version=3;
  log_webhook_id: 382609729802862592