name: build-modix
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1
        with:
          version: latest
          install: true

      - name: Run Tests
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          target: dotnet-test
          push: false
          cache-to: type=gha, scope=${{github.repository}}
          cache-from: type=gha, scope=${{github.repository}}

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract Docker metadata for main build
        id: meta
        uses: docker/metadata-action@v3.4.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ github.event_name == 'push' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: github.event_name == 'push'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: type=gha, scope=${{github.repository}}
          cache-from: type=gha, scope=${{github.repository}}

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (secrets.MODIX_UPDATE_WEBHOOK != null || secrets.MODIX_UPDATE_WEBHOOK != '') }}
    steps:
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
        
      - name: Signal New Build
        uses: enflo/curl-action@fabe347922c7a9e88bafa15c4b7d6326ea802695
        with:
          curl: -X POST ${{ secrets.MODIX_UPDATE_WEBHOOK }}
